apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: store-deployment
  labels:
    system: a01
    group: base
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
      - name: store-flask-svc
        image: adxautomationbase.azurecr.io/store:0.10.0
        ports:
        - containerPort: 80
        env:
        - name: A01_DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: store-secrets
              key: dburi
        - name: A01_INTERNAL_COMKEY
          valueFrom:
            secretKeyRef:
              name: store-secrets
              key: comkey 
      imagePullSecrets:
      - name: adxautomationbase-registry
---
apiVersion: v1
kind: Service
metadata:
  name: store-internal-svc
  labels:
    system: a01
    group: base
spec:
  ports:
  - port: 80
  selector:
    app: store
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: email-deployment
  labels:
    system: a01
    group: base
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
      - name: email-flask-svc
        image: adxautomationbase.azurecr.io/email:0.2.0
        ports:
        - containerPort: 80
        env:
        - name: A01_STORE_NAME
          value: store-internal-svc
        - name: A01_INTERNAL_COMKEY
          valueFrom:
            secretKeyRef:
              name: store-secrets
              key: comkey
        - name: A01_REPORT_SMTP_SERVER
          valueFrom:
            secretKeyRef:
              name: email
              key: server
        - name: A01_REPORT_SENDER_ADDRESS
          valueFrom:
            secretKeyRef:
              name: email
              key: username
        - name: A01_REPORT_SENDER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: email
              key: password
      imagePullSecrets:
      - name: adxautomationbase-registry
---
apiVersion: v1
kind: Service
metadata:
  name: email-internal-svc
  labels:
    system: a01
    group: base
spec:
  ports:
  - port: 80
  selector:
    app: email
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: email-cronjob
  labels:
    system: a01
    group: base
  spec:
    schedule: 7 0 * * 1 # mondays at 7 AM
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              app: email
          spec:
            containers:
              - name: email-weekly-svc
                image: adxautomationbase.azurecr.io/email-weekly:0.1.0
                args:
                - python
                - /app/main.py
                env:
                - name: A01_STORE_NAME
                  value: store-internal-svc
                - name: A01_INTERNAL_COMKEY
                  valueFrom:
                    secretKeyRef:
                      name: store-secrets
                      key: comkey
                - name: A01_REPORT_SMTP_SERVER
                  valueFrom:
                    secretKeyRef:
                      name: email
                      key: server
                - name: A01_REPORT_SENDER_ADDRESS
                  valueFrom:
                    secretKeyRef:
                      name: email
                      key: username
                - name: A01_REPORT_SENDER_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: email
                      key: password
                - name: PRODUCTS
                  valueFrom:
                    secretKeyRef:
                      name: email
                      key: products.weekly
            imagePullSecrets:
            - name: adxautomationbase-registry
